version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-test"
s3_bucket = "aws-sam-test"
s3_prefix = "sam-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
