AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  usermanagement

  Sample SAM Template for usermanagement templates

telemetryEnabled:
    description: 'Set to `false` to disable telemetry'
    required: false
    default: 'true'
