version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "aws-sam-cli-managed-one-pipeline-reso-PipelineUser-14HNWW795HYKU"

[one]
[one.pipeline_bootstrap]
[one.pipeline_bootstrap.parameters]
pipeline_execution_role = "aws-sam-cli-managed-one-pipe-PipelineExecutionRole-UT7F3KVIA89K"
cloudformation_execution_role = "aws-sam-cli-managed-one-p-CloudFormationExecutionR-X0BYHU8Z28U1"
artifacts_bucket = ""
image_repository = ""
region = "us-east-1"

[two]
[two.pipeline_bootstrap]
[two.pipeline_bootstrap.parameters]
pipeline_execution_role = "aws-sam-cli-managed-one-pipe-PipelineExecutionRole-UT7F3KVIA89K"
cloudformation_execution_role = "aws-sam-cli-managed-one-p-CloudFormationExecutionR-X0BYHU8Z28U1"
artifacts_bucket = ""
image_repository = ""
region = "us-east-1"
