name: PR Automerger
          
on:
  pull_request:
    branches: 
      - main
  workflow_run:
    workflows: [unit-test]
    types: 
      - completed
    
jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps: 
      - id: pr-automerge
        name: pr-automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.PR_TOKEN }}"
          MERGE_LABELS: "pr-automerge,!wip, !work in progress"
          MERGE_REMOVE_LABELS: "pr-automerge"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_ERROR_FAIL: "true"
